name: 🚀 Deploy workflow on production environment

on:
  push:
    tags:
      - 'v*.*' # 'v'로 시작하는 모든 태그 패턴

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Zip the build
        run: zip -r build.zip .

      - name: Deploy to AWS CodeDeploy
        run: |
          echo "Deploying to production..."
          # Your deployment script here

      - name: Access to Aws
        run: |
          aws deploy create-deployment \
            --application-name ${{ secret.AWS_CODE_DEPLOY_APP_NAME }} \
            --deployment-group-name ${{ secret.AWS_CODE_DEPLOY_GROUP_NAME }} \
            --github-location repository=kidoc/bookmark-note,commitId=${{ github.sha }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'ap-northeast-2'
